-- AlterTable
ALTER TABLE "Team" ADD COLUMN     "adminUserId" INTEGER NOT NULL DEFAULT 2;

-- AddForeignKey
ALTER TABLE "Team" ADD FOREIGN KEY("adminUserId")REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
