FROM node:15

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY . .
COPY .env.production .env

RUN npm run build


ENV NODE_ENV production


EXPOSE 9000
CMD ["node", "dist/index.js"]
USER node